spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mydatabase
    username: OBFUSCATED_USERNAME_HERE
    password: OBFUSCATED_PASSWORD_HERE
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create-drop
springdoc:
  swagger-ui:
    defaultModelsExpandDepth: 0